version: '2'
services:
 mysql:  
  image: mysql
  container_name: pwcho2018_81928
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_DATABASE: database
   MYSQL_USER: sduda
   MYSQL_PASSWORD: password 
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  networks: 
   bridge_zadanie_1:
    ipv4_address: 10.0.10.3
  ports:
   - 3306:3306
 java:
  image: dudasylwia/docker
  container_name: java
  depends_on:
   - mysql
  links:
   - mysql
  networks:
   bridge_zadanie_1:
  ports:
   - 8080:8080
networks:
 bridge_zadanie_1:
  driver: bridge
  ipam:
   config:
    - subnet: 10.0.10.0/24
      gateway: 10.0.10.1


